import { Model } from "@/model/utils";
import { Catalog, InterfaceWithModels, Item } from "@/types";
import { Map } from "immutable";
import { sq } from "@quri/squiggle-lang";

// Note: Much of this was generated by this file:
// https://observablehq.com/d/98cbe0073226a5f9

function getCatalog(): Catalog {
  const items: Item[] = [
    {
      id: "one_human_qaly",
      name: "1 human QALY (quality-adjusted life-year)",
      clusterId: "sentient_welfare"
    },
    {
      id: "cow_value_per_year_of_life",
      name: "cow value per year of life",
      clusterId: "sentient_welfare",
    },
    {
      id: "cow_value_per_lifetime",
      name: "cow value per lifetime",
      clusterId: "sentient_welfare",
    },
    {
      id: "cow_value_per_calorie",
      name: "cow value per calorie",
      clusterId: "sentient_welfare",
    },
    {
      id: "pig_value_per_year_of_life",
      name: "pig value per year of life",
      clusterId: "sentient_welfare",
    },
    {
      id: "pig_value_per_lifetime",
      name: "pig value per lifetime",
      clusterId: "sentient_welfare",
    },
    {
      id: "pig_value_per_calorie",
      name: "pig value per calorie",
      clusterId: "sentient_welfare",
    },
    {
      id: "chicken_value_per_year_of_life",
      name: "chicken value per year of life",
      clusterId: "sentient_welfare",
    },
    {
      id: "chicken_value_per_lifetime",
      name: "chicken value per lifetime",
      clusterId: "sentient_welfare",
    },
    {
      id: "chicken_value_per_calorie",
      name: "chicken value per calorie",
      clusterId: "sentient_welfare",
    },
    {
      id: "salmon_value_per_year_of_life",
      name: "salmon value per year of life",
      clusterId: "sentient_welfare",
    },
    {
      id: "salmon_value_per_lifetime",
      name: "salmon value per lifetime",
      clusterId: "sentient_welfare",
    },
    {
      id: "salmon_value_per_calorie",
      name: "salmon value per calorie",
      clusterId: "sentient_welfare",
    },
    {
      id: "fish_welfare_initiative_2022_value_estimate",
      name: "Fish Welfare Initiative (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "open_wing_alliance_2022_value_estimate",
      name: "Open Wing Alliance (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "beyond_meat_2022_value_estimate",
      name: "Beyond Meat (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "faunalytics_2022_value_estimate",
      name: "Faunalytics (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "the_humane_league_2022_value_estimate",
      name: "The Humane League (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "good_food_institute_2022_value_estimate",
      name: "Good Food Institute (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "wild_animal_inititative_2022_value_estimate",
      name: "Wild Animal Inititative (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "chkd_2022_value_estimate",
      name: "Çiftlik Hayvanlarını Koruma Derneği (CHKD) (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "compassion_usa_2022_value_estimate",
      name: "Compassion USA (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "dansk_vegetarisk_forening_2022_value_estimate",
      name: "Dansk Vegetarisk Forening (DVF) (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "dharma_voices_for_animals_2022_value_estimate",
      name: "Dharma Voices for Animals (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "federation_of_indian_animal_protection_organisations_2022_value_estimate",
      name: "Federation of Indian Animal Protection Organisations (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "material_innovation_initiative_2022_value_estimate",
      name: "Material Innovation Initiative (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "mercy_for_animals_2022_value_estimate",
      name: "Mercy For Animals (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "new_harvest_2022_value_estimate",
      name: "New Harvest (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "sinergia_animal_2022_value_estimate",
      name: "Sinergia Animal (2022)",
      clusterId: "sentient_welfare_interventions",
    },
    {
      id: "xiaobuvegan_2022_value_estimate",
      name: "xiaobuVEGAN (2022)",
      clusterId: "sentient_welfare_interventions",
    }
  ];

  return {
    id: "relative-values-animals-2023-04",
    title: "Relative values for animals and animal charities",
    items,
    recommendedUnit: "funder_openphil_2020",
    clusters: {
      sentient_welfare: {
        name: "sentient_welfare",
        color: "#3B42aC",
        recommendedUnit: "salmon_value_per_year_of_life",
      },
      sentient_welfare_interventions: {
        name: "sentient_welfare_interventions",
        color: "#3B42aC",
        recommendedUnit: "fish_welfare_initiative_2022_value_estimate",
      }
    },
  };
}

function getTextModel(): Model {
  return {
    id: "relative-values-animals-2023-04",
    title: "Relative values for animals and animal charities",
    author: "Nuño Sempere",
    mode: "text",
    code: sq`
    fn(a,b) = [normal(0,1), normal(0,1 )]
`,
  };
}

export const catalog = getCatalog();
export const models = [getTextModel()];
