import { Model } from "@/model/utils";
import { Catalog, InterfaceWithModels, Item } from "@/types";
import { Map } from "immutable";

// Note: Much of this was generated by this file:
// https://observablehq.com/d/98cbe0073226a5f9

function getCatalog(): Catalog {
  const items: Item[] = [
    {
      id: "walking_in_nature_10min",
      name: "Walking in Nature (10 min)",
      clusterId: "physicalAndMentalHealthActivities",
    },
    {
      id: "stretching_10min",
      name: "Stretching (10 min)",
      clusterId: "physicalAndMentalHealthActivities",
    },
    {
      id: "biking_10min",
      name: "Biking (10 min)",
      clusterId: "physicalAndMentalHealthActivities",
    },
    {
      id: "meditation_10min",
      name: "Meditation (10 min)",
      clusterId: "physicalAndMentalHealthActivities",
    },
    {
      id: "taking_stairs_5floors",
      name: "Taking Stairs (5 floors)",
      clusterId: "physicalAndMentalHealthActivities",
    },
    {
      id: "strength_training_10min",
      name: "Strength Training (10 min)",
      clusterId: "physicalAndMentalHealthActivities",
    },

    {
      id: "flu_vaccine_1",
      name: "Flu Vaccine (1 time)",
      clusterId: "medsSupplements",
    },
    {
      id: "orthomega_fishoil_1cap",
      name: "Orthomega Fish Oil (1 cap)",
      clusterId: "medsSupplements",
    },
    {
      id: "enchanced_zinc_lozenges_6cap_assuming_sick",
      name: "Enhanced Zinc Lozenges (6 cap, assuming sick)",
      clusterId: "medsSupplements",
    },
    {
      id: "eating_yogurt_1serving",
      name: "Eating Yogurt (1 serving)",
      clusterId: "goodFood",
    },
    {
      id: "whole_grain_bread_1slice",
      name: "Whole Grain Bread (1 slice)",
      clusterId: "goodFood",
    },
    {
      id: "drinking_water_8oz",
      name: "Drinking Water (8 Oz)",
      clusterId: "goodFood",
    },
    {
      id: "green_tea_1cup",
      name: "Drinking Green Tea (1 cup)",
      clusterId: "goodFood",
    },
    {
      id: "turmeric_1tsp",
      name: "Taking Turmeric (1 tsp)",
      clusterId: "goodFood",
    },
    {
      id: "blueberries_1cup",
      name: "Eating Blueberries (1 cup)",
      clusterId: "goodFood",
    },
    {
      id: "extra_primary_sleep_10min",
      name: "Getting extra primary sleep (10 min)",
      clusterId: "selfCarePractices",
    },
    {
      id: "laughing_5min",
      name: "Laughing (5 min)",
      clusterId: "selfCarePractices",
    },
    {
      id: "social_interaction_30min",
      name: "Social Interaction (30 min)",
      clusterId: "selfCarePractices",
    },
    {
      id: "washing_hands_30sec",
      name: "Washing hands (30 sec)",
      clusterId: "selfCarePractices",
    },
    {
      id: "wearing_face_mask_1day",
      name: "Wearing Face Mask (1 day)",
      clusterId: "selfCarePractices",
    },
    {
      id: "brushing_teeth_2min",
      name: "Brushing Teeth (2 min)",
      clusterId: "selfCarePractices",
    },
    {
      id: "flossing_1time",
      name: "Flossing (1 time)",
      clusterId: "selfCarePractices",
    },
    {
      id: "sunscreen_application_1",
      name: "Sunscreen application (1 time)",
      clusterId: "selfCarePractices",
    },
    {
      id: "blackcoffee_1cup",
      name: "Drinking black coffee (1 cup)",
      clusterId: "unhealthyFoodOrDrink",
    },
    {
      id: "diet_coke_250ml",
      name: "Drinking diet coke (250 mL)",
      clusterId: "unhealthyFoodOrDrink",
    },
    {
      id: "deep_fried_food_1serving",
      name: "Eating deep fried food (1 serving)",
      clusterId: "unhealthyFoodOrDrink",
    },
    {
      id: "processed_meat_1serving",
      name: "Eating processed meat (1 serving)",
      clusterId: "unhealthyFoodOrDrink",
    },
    {
      id: "brown_sugar_10g",
      name: "Taking brown sugar (10 g)",
      clusterId: "sweeteners",
    },
    {
      id: "white_sugar_10g",
      name: "Taking white sugar (10 g)",
      clusterId: "sweeteners",
    },
    {
      id: "stevia_1pack",
      name: "Taking stevia (1 pack)",
      clusterId: "sweeteners",
    },
    {
      id: "redwine_1oz",
      name: "Drinking red wine (1 oz)",
      clusterId: "wine",
    },
    {
      id: "redwine_10oz",
      name: "Drinking red wine (10 oz)",
      clusterId: "wine",
    },
    {
      id: "vomiting_2min",
      name: "Vomiting (2 min)",
      clusterId: "negativeHealthCondition",
    },
    {
      id: "mediocre_headache_10min",
      name: "Having mediocre headache (10 min)",
      clusterId: "negativeHealthCondition",
    },
    {
      id: "sitting_1hour",
      name: "Sitting (1 hour)",
      clusterId: "badHabits",
    },
    {
      id: "screen_time_1hour",
      name: "Screen time (1 hour)",
      clusterId: "badHabits",
    },
    {
      id: "smoking_cigarette_1",
      name: "Smoking cigarette (1 stick)",
      clusterId: "badHabits",
    },
  ];

  return {
    id: "health-interventions",
    title: "Health Interventions",
    items,
    recommendedUnit: "walking_in_nature_10min",
    clusters: {
      physicalAndMentalHealthActivities: {
        name: "Physical and Mental Health Activities",
        color: "#00B7C2",
      },
      medsSupplements: {
        name: "Meds and Supplements",
        color: "#6E5BA5",
      },
      goodFood: {
        name: "Good Food",
        color: "#73AF48",
      },
      selfCarePractices: {
        name: "Self-Care Practices",
        color: "#F4B940",
      },
      unhealthyFoodOrDrink: {
        name: "Unhealthy Food or Drink",
        color: "#E6542B",
      },
      sweeteners: {
        name: "Sweeteners",
        color: "#DB828C",
      },
      wine: {
        name: "Wine",
        color: "#A53241",
      },
      negativeHealthCondition: {
        name: "Negative Health Condition",
        color: "#2F2D2E",
      },
      badHabits: {
        name: "Bad Habits",
        color: "#8B572A",
      },
    },
  };
}

function getModel(): Model {
  return {
    id: "health-interventions",
    title: "Health Interventions ",
    author: "GPT-4",
    mode: "text",
    code: `
    brown_sugar_10g = SampleSet.fromDist(-(0.5 to 3))
    turmeric_1tsp = SampleSet.fromDist(0.1 to 2) // Turmeric has anti-inflammatory properties, but the benefits may vary
    blueberries_1cup = SampleSet.fromDist(0.5 to 5) // Blueberries are rich in antioxidants, promoting overall health
    smoking_cigarette_1 = SampleSet.fromDist(-(1 to 10)) // Smoking has severe negative health effects, such as lung cancer and heart disease
    redwine_1oz = -0.5 to 2
    meditation_10min = SampleSet.fromDist(0.5 to 10)
    orthomega_fishoil_1cap = SampleSet.fromDist(0.1 to 3)
    laughing_5min = SampleSet.fromDist(0.5 to 3)
    stretching_10min = SampleSet.fromDist(0.2 to 3.5)
    
    items = {
      walking_in_nature_10min: pointMass(1),
      stretching_10min: stretching_10min,
      biking_10min: stretching_10min*(3 to 10),
      meditation_10min: meditation_10min,// Meditation can help reduce stress and improve mental health
      taking_stairs_5floors: stretching_10min*(1 to 5),// Taking stairs increases physical activity, promoting overall health
      strength_training_10min: stretching_10min*(2 to 6), // Strength training improves muscle strength, bone density, and overall health
      
      flu_vaccine_1: 5 to 25,// Flu vaccine reduces the risk of flu-related complications
      orthomega_fishoil_1cap: orthomega_fishoil_1cap, //I'm skeptical it has a major effect
      enchanced_zinc_lozenges_6cap_assuming_sick: orthomega_fishoil_1cap*(5 to 20),
      eating_yogurt_1serving: 0.2 to 2.5, // Yogurt is a good source of probiotics, promoting gut health
      whole_grain_bread_1slice: 0.1 to 2,// Whole grain bread provides essential nutrients and fiber
      drinking_water_8oz: 0.1 to 2, // Drinking water is essential for hydration and overall health
      green_tea_1cup: turmeric_1tsp*(0.2 to 3),// Green tea has antioxidants and may provide various health benefits
      turmeric_1tsp: turmeric_1tsp,
      blueberries_1cup: blueberries_1cup,
      
      extra_primary_sleep_10min: 0.2 to 3,
      laughing_5min: laughing_5min, // Laughing can improve mood and provide short-term stress relief
      social_interaction_30min: laughing_5min*(1 to 5),// Social interaction promotes mental health and well-being
      washing_hands_30sec: 0.1 to 5,
      wearing_face_mask_1day: 0.2 to 1,
      brushing_teeth_2min: 1 to 4, // Brushing teeth prevents cavities and gum disease
      flossing_1time: 0.5 to 3, // Flossing helps remove plaque, reducing the risk of cavities and gum disease
      sunscreen_application_1: 0.5 to 10,// Sunscreen application reduces the risk of skin cancer and premature aging
      
      blackcoffee_1cup: -10 to 2, //The tolerance it gives you seems pretty negative-EV, after the first benefits
      diet_coke_250ml: -2 to 0.2,
      deep_fried_food_1serving: -(0.5 to 6), // Deep-fried food is generally high in unhealthy fats, leading to negative health effects
      processed_meat_1serving: -(0.5 to 3),// Processed meats are associated with increased risk of cancer and heart disease
      
      brown_sugar_10g: brown_sugar_10g,
      white_sugar_10g: brown_sugar_10g * (.7 to 1), //Probably very similar to brown sugar
      stevia_1pack: brown_sugar_10g * (0.001 to 0.2), //probably correlated with sugar
      redwine_1oz: redwine_1oz,
      redwine_10oz: redwine_1oz * 10,
    
      vomiting_2min: -(5 to 100),
      diarrhea_1episode: -(3 to 50), // Diarrhea can lead to dehydration and loss of nutrients, negatively impacting health
      mediocre_headache_10min: -(1 to 10),
      
      sitting_1hour: -(0.1 to 0.5), // Prolonged sitting can lead to negative health effects like obesity and heart disease
      screen_time_1hour: -(0.1 to 1),// Excessive screen time may lead to eye strain and other negative health effects
      smoking_cigarette_1: smoking_cigarette_1
      
      
    }
    withSampleSetValue(item) = SampleSet.fromDist(item)
    items = Dict.map(items, withSampleSetValue)
    
    fn(intervention1, intervention2) = [items[intervention1], items[intervention2]]
`,
  };
}

export const catalog = getCatalog();
export const models = [getModel()];
