image:
  name: harbor.k8s.quantifieduncertainty.org/main/metaforecast
  pullSecret: dockerconfig
  tag: latest # In production for QURI deployment, we use `argocd app set` to update the tag

# Secret; you should create this in your k8s cluster.
# Env variables documented in `env.example`.
envSecret: metaforecast-env

# Metaforecast was shut down on July 9, 2026 — all scraper cronjobs removed.
jobs: {}
