image:
  name: registry.k8s.quantifieduncertainty.org/metaforecast
  pullSecret: dockerconfig
  tag: latest # In production for QURI deployment, we use argocd-image-updater to update the tag

# Secret; you should create this in your k8s cluster.
# Env variables documented in `env.example`.
envSecret: metaforecast-env

jobs:
  scheduler:
    command: ["pnpm", "run", "cli", "all"]
    schedule: "0 3 * * *" # every day at 3am
  frontpage:
    command: ["pnpm", "run", "cli", "frontpage"]
    schedule: "0 6 * * *" # every day at 6am
  manifold-fetch-new:
    command: ["pnpm", "run", "cli", "manifold", "fetch-new"]
    schedule: "*/5 * * * *" # every 5 minutes
