{{- range $jobname, $job := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $jobname }}
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $jobname }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ $jobname }}
    spec:
      imagePullSecrets:
      - name: dockerconfig
      containers:
        - name: server
          image: "{{ $.Values.image.name }}:{{ required "tag is required" $.Values.image.tag }}"
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: {{ $.Values.envSecretName }}
          command: 
            {{- $job.command | required "command is required" | toYaml | nindent 10 }}
---
{{- end }}
 