// auto-generated by `publish-all.ts`, don't touch
export const squiggleVersions = ["0.8.6", "0.8.5", "dev"] as const;

export type SquiggleVersion = (typeof squiggleVersions)[number];

// auto-generated by `publish-all.ts`, don't touch
export const defaultSquiggleVersion: SquiggleVersion = "0.8.6";

export function checkSquiggleVersion(
  version: string
): version is SquiggleVersion {
  return (squiggleVersions as readonly string[]).includes(version);
}
