// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Assignment = 2,
  String = 4,
  Boolean = 5,
  Number = 7,
  Void = 8,
  LambdaExpr = 9,
  VariableName = 12,
  FunctionName = 19,
  Statement = 34
