// Model selection and pricing
export type ModelConfig = {
  provider: "anthropic" | "openai" | "openrouter";
  model: string;
  inputRate: number;
  outputRate: number;
  contextWindow: number;
  maxTokens?: number;
  name: string;
  id: string;
  allowsSystemPrompt: boolean;
};

// After some discussion, we decided to store this as an array of objects instead of a record. This is because it can be a pain to iterate and filter over records, and there aren't any significant performance benefits to using a record for this data.
export const MODEL_CONFIGS = [
  {
    id: "o1-preview",
    provider: "openai",
    model: "o1-preview",
    inputRate: 15,
    outputRate: 60,
    contextWindow: 128000,
    maxTokens: 32768,
    name: "o1 Preview",
    allowsSystemPrompt: false,
  },
  {
    id: "o1-mini",
    provider: "openai",
    model: "o1-mini-2024-09-12",
    inputRate: 3,
    outputRate: 12,
    contextWindow: 128000,
    maxTokens: 65536,
    name: "o1 Mini",
    allowsSystemPrompt: false,
  },
  {
    id: "GPT4o",
    provider: "openai",
    model: "gpt-4o-2024-08-06",
    inputRate: 2.5,
    outputRate: 10,
    contextWindow: 128000,
    name: "GPT-4o",
    allowsSystemPrompt: true,
  },
  {
    id: "GPT4-Fine-Tuned",
    provider: "openai",
    model:
      "ft:gpt-4o-2024-08-06:quantified-uncertainty-research-institute:squiggle-v02:ACWwi8V1",
    inputRate: 3.75,
    outputRate: 15,
    contextWindow: 128000,
    name: "GPT-4o Fine-Tuned",
    allowsSystemPrompt: false,
  },
  {
    id: "GPT4-mini",
    provider: "openai",
    model: "gpt-4o-mini-2024-07-18",
    inputRate: 0.15,
    outputRate: 0.6,
    contextWindow: 128000,
    name: "GPT-4o mini",
    allowsSystemPrompt: true,
  },
  {
    id: "GPT-5-1-Codex",
    provider: "openrouter",
    model: "openai/gpt-5.1-codex",
    inputRate: 1.25,
    outputRate: 10,
    contextWindow: 400000,
    maxTokens: 8192,
    name: "OpenAI: GPT-5.1-Codex",
    allowsSystemPrompt: true,
  },
  {
    id: "GPT-5-1-Codex-Mini",
    provider: "openrouter",
    model: "openai/gpt-5.1-codex-mini",
    inputRate: 0.25,
    outputRate: 2,
    contextWindow: 400000,
    maxTokens: 8192,
    name: "OpenAI: GPT-5.1-Codex-Mini",
    allowsSystemPrompt: true,
  },
  {
    id: "GPT-5-3-Codex",
    provider: "openrouter",
    model: "openai/gpt-5.3-codex",
    inputRate: 1.75,
    outputRate: 14,
    contextWindow: 400000,
    maxTokens: 8192,
    name: "OpenAI: GPT-5.3-Codex",
    allowsSystemPrompt: true,
  },
  {
    id: "Claude-4-5-Sonnet",
    provider: "anthropic",
    model: "claude-sonnet-4-5-20250929",
    inputRate: 3,
    outputRate: 15,
    contextWindow: 200000,
    maxTokens: 8192,
    name: "Claude Sonnet 4.5",
    allowsSystemPrompt: true,
  },
  {
    id: "Claude-3-7-Sonnet",
    provider: "anthropic",
    model: "claude-3-7-sonnet-latest",
    inputRate: 3,
    outputRate: 15,
    contextWindow: 200000,
    maxTokens: 8192,
    name: "Claude Sonnet 3.7",
    allowsSystemPrompt: true,
  },
  {
    id: "Claude-3-5-Haiku",
    provider: "anthropic",
    model: "claude-3-5-haiku-latest",
    inputRate: 1.0,
    outputRate: 3.0,
    contextWindow: 200000,
    maxTokens: 8192,
    name: "Claude Haiku 3.5",
    allowsSystemPrompt: true,
  },
  {
    id: "Claude-4-5-Haiku",
    provider: "anthropic",
    model: "claude-haiku-4-5",
    inputRate: 1.0,
    outputRate: 5.0,
    contextWindow: 200000,
    maxTokens: 8192,
    name: "Claude Haiku 4.5",
    allowsSystemPrompt: true,
  },
  {
    id: "Claude-4-5-Opus",
    provider: "anthropic",
    model: "claude-opus-4-5-20251101",
    inputRate: 5,
    outputRate: 25,
    contextWindow: 200000,
    maxTokens: 8192,
    name: "Claude Opus 4.5",
    allowsSystemPrompt: true,
  },
  {
    id: "Claude-Sonnet-5",
    provider: "anthropic",
    model: "claude-sonnet-5",
    inputRate: 3,
    outputRate: 15,
    contextWindow: 1000000,
    maxTokens: 8192,
    name: "Claude Sonnet 5",
    allowsSystemPrompt: true,
  },
  {
    id: "Claude-Opus-4-8",
    provider: "anthropic",
    model: "claude-opus-4-8",
    inputRate: 5,
    outputRate: 25,
    contextWindow: 1000000,
    maxTokens: 8192,
    name: "Claude Opus 4.8",
    allowsSystemPrompt: true,
  },
  {
    id: "Gemini-3-1-Pro-Preview",
    provider: "openrouter",
    model: "google/gemini-3.1-pro-preview",
    inputRate: 2,
    outputRate: 12,
    contextWindow: 1048576,
    maxTokens: 8192,
    name: "Google: Gemini 3.1 Pro Preview",
    allowsSystemPrompt: true,
  },
  {
    id: "DeepSeek-V4-Pro",
    provider: "openrouter",
    model: "deepseek/deepseek-v4-pro",
    inputRate: 0.435,
    outputRate: 0.87,
    contextWindow: 1048576,
    maxTokens: 8192,
    name: "DeepSeek: DeepSeek V4 Pro",
    allowsSystemPrompt: true,
  },
  {
    id: "GLM-5-2",
    provider: "openrouter",
    model: "z-ai/glm-5.2",
    inputRate: 0.728,
    outputRate: 2.288,
    contextWindow: 1048576,
    maxTokens: 8192,
    name: "Z.AI: GLM 5.2",
    allowsSystemPrompt: true,
  },
  {
    id: "Kimi-K2-7-Code",
    provider: "openrouter",
    model: "moonshotai/kimi-k2.7-code",
    inputRate: 0.74,
    outputRate: 3.5,
    contextWindow: 262144,
    maxTokens: 8192,
    name: "MoonshotAI: Kimi K2.7 Code",
    allowsSystemPrompt: true,
  },
  {
    id: "MiniMax-M3",
    provider: "openrouter",
    model: "minimax/minimax-m3",
    inputRate: 0.3,
    outputRate: 1.2,
    contextWindow: 1048576,
    maxTokens: 8192,
    name: "MiniMax: MiniMax M3",
    allowsSystemPrompt: true,
  },
  {
    id: "MiMo-V2-5-Pro",
    provider: "openrouter",
    model: "xiaomi/mimo-v2.5-pro",
    inputRate: 0.435,
    outputRate: 0.87,
    contextWindow: 1048576,
    maxTokens: 8192,
    name: "Xiaomi: MiMo-V2.5-Pro",
    allowsSystemPrompt: true,
  },
  {
    id: "GLM-4-6",
    provider: "openrouter",
    model: "z-ai/glm-4.6",
    inputRate: 0.43,
    outputRate: 1.74,
    contextWindow: 202752,
    maxTokens: 8192,
    name: "Z.AI: GLM 4.6",
    allowsSystemPrompt: true,
  },
  {
    id: "Gemini-2-5-Pro",
    provider: "openrouter",
    model: "google/gemini-2.5-pro",
    inputRate: 1.25,
    outputRate: 10,
    contextWindow: 1048576,
    maxTokens: 8192,
    name: "Google: Gemini 2.5 Pro",
    allowsSystemPrompt: true,
  },
] as const satisfies ModelConfig[];

export type LlmId = (typeof MODEL_CONFIGS)[number]["id"];
export type LlmName = (typeof MODEL_CONFIGS)[number]["name"];

export const DEFAULT_LLM_ID: LlmId = "Claude-Sonnet-5";

// Models that should be visible in the UI
const UI_VISIBLE_MODEL_IDS: LlmId[] = [
  "Claude-Sonnet-5",
  "Claude-Opus-4-8",
  "Claude-4-5-Haiku",
  "Gemini-3-1-Pro-Preview",
  "DeepSeek-V4-Pro",
  "GLM-5-2",
  "Kimi-K2-7-Code",
  "MiniMax-M3",
  "MiMo-V2-5-Pro",
];

export const UI_VISIBLE_MODELS = MODEL_CONFIGS.filter((model) =>
  UI_VISIBLE_MODEL_IDS.includes(model.id)
);
