-- CreateEnum
CREATE TYPE "VariableType" AS ENUM ('NUMBER', 'STRING', 'LIST', 'DICT', 'BOOLEAN', 'CALCULATOR', 'FUNCTION', 'SAMPLE_SET_DISTRIBUTION', 'POINT_SET_DISTRIBUTION', 'SYMBOLIC_DISTRIBUTION', 'OTHER');

-- AlterTable
ALTER TABLE "ModelExport" ADD COLUMN     "variableType" "VariableType" NOT NULL DEFAULT 'OTHER';
