name: Prisma Migrate Production DB

on:
  workflow_dispatch:
    inputs:
      run_hub_migration:
        description: "Run Hub database migration"
        type: boolean
        default: true
        required: false
      run_metaforecast_migration:
        description: "Run Metaforecast database migration"
        type: boolean
        default: true
        required: false

jobs:
  migrate-hub:
    if: ${{ inputs.run_hub_migration }}
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: ./.github/actions/install

      - name: Migrate Hub
        working-directory: ./internal-packages/hub-db
        env:
          DATABASE_URL: "${{ secrets.DATABASE_DIRECT_URL }}"
        run: npx prisma migrate deploy

  migrate-metaforecast:
    if: ${{ inputs.run_metaforecast_migration }}
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install

      - name: Migrate Metaforecast
        working-directory: ./internal-packages/metaforecast-db
        env:
          METAFORECAST_DB_URL: "${{ secrets.METAFORECAST_DATABASE_URL }}"
        run: npx prisma migrate deploy
